dna = input('Введите последовательность ДНК: ')
dna_upper = dna.upper()
length = len(dna_upper)
countA = dna.count('A')
countT = dna.count('T')
countG = dna.count('G')
countC = dna.count('C')
print(f'Последовательность в верхнем регистре: {dna_upper}')
print(f'Подсчёт нуклеотидов:\nA:{countA}\nT:{countT}\nG:{countG}\nC:{countC}')
print(f'Общая длина: {length} нуклеотидов')
print(f'Процентное содержание:\nA:{countA * 100 / length:.2f}\nT:{countT * 100 / length:.2f}\nG:{countG * 100 / length:.2f}\nC:{countC * 100 / length:.2f}')